# Generated by Django 4.2.30 on 2026-07-06 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'risikorammeverk',
                'verbose_name_plural': 'Risiko: rammeverk',
                'ordering': ['title'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='RiskFrameworkNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('nummer', models.PositiveSmallIntegerField(default=1, verbose_name='Nummer')),
                ('title', models.CharField(max_length=300, verbose_name='Tittel')),
                ('forklaring', models.TextField(blank=True, default='', verbose_name='Forklaring')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('archived', 'Arkivert')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('rekkefolge', models.PositiveIntegerField(default=0, verbose_name='Rekkefølge')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='systemoversikt.riskframework', verbose_name='Rammeverk')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='systemoversikt.riskframeworknode', verbose_name='Overordnet kategori')),
            ],
            options={
                'verbose_name': 'risikorammeverk-node',
                'verbose_name_plural': 'Risiko: rammeverk-noder',
                'ordering': ['framework', 'parent__rekkefolge', 'parent__nummer', 'rekkefolge', 'nummer'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('framework', 'parent', 'nummer')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalRiskVirksomhetNodeAssessment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('konsekvens_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Konsekvens')),
                ('sannsynlighet_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sannsynlighet')),
                ('begrunnelse', models.TextField(blank=True, default='', verbose_name='Begrunnelse')),
                ('sist_revidert', models.DateField(blank=True, null=True, verbose_name='Sist revidert')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('framework_node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revidert_av', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revidert av')),
                ('virksomhet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.virksomhet', verbose_name='Virksomhet')),
            ],
            options={
                'verbose_name': 'historical risikovurdering rammeverk-node',
                'verbose_name_plural': 'historical Risiko: virksomhetsvurderinger rammeverk',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskScenarioFrameworkLink',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('mapped_at', models.DateTimeField(blank=True, editable=False, verbose_name='Kartlagt')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notat')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('framework_node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mapped_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kartlagt av')),
                ('scenario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskscenario', verbose_name='Risikoscenario')),
            ],
            options={
                'verbose_name': 'historical risikoscenario-rammeverk-kobling',
                'verbose_name_plural': 'historical Risiko: scenario-rammeverk-koblinger',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskFrameworkNode',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('nummer', models.PositiveSmallIntegerField(default=1, verbose_name='Nummer')),
                ('title', models.CharField(max_length=300, verbose_name='Tittel')),
                ('forklaring', models.TextField(blank=True, default='', verbose_name='Forklaring')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('archived', 'Arkivert')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('rekkefolge', models.PositiveIntegerField(default=0, verbose_name='Rekkefølge')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('framework', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframework', verbose_name='Rammeverk')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframeworknode', verbose_name='Overordnet kategori')),
            ],
            options={
                'verbose_name': 'historical risikorammeverk-node',
                'verbose_name_plural': 'historical Risiko: rammeverk-noder',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskFramework',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical risikorammeverk',
                'verbose_name_plural': 'historical Risiko: rammeverk',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RiskVirksomhetNodeAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('konsekvens_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Konsekvens')),
                ('sannsynlighet_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sannsynlighet')),
                ('begrunnelse', models.TextField(blank=True, default='', verbose_name='Begrunnelse')),
                ('sist_revidert', models.DateField(blank=True, null=True, verbose_name='Sist revidert')),
                ('framework_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virksomhet_assessments', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('revidert_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_framework_assessments_revised', to=settings.AUTH_USER_MODEL, verbose_name='Revidert av')),
                ('virksomhet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_framework_assessments', to='systemoversikt.virksomhet', verbose_name='Virksomhet')),
            ],
            options={
                'verbose_name': 'risikovurdering rammeverk-node',
                'verbose_name_plural': 'Risiko: virksomhetsvurderinger rammeverk',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('virksomhet', 'framework_node')},
            },
        ),
        migrations.CreateModel(
            name='RiskScenarioFrameworkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('mapped_at', models.DateTimeField(auto_now_add=True, verbose_name='Kartlagt')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notat')),
                ('framework_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_links', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_framework_links_created', to=settings.AUTH_USER_MODEL, verbose_name='Kartlagt av')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_links', to='systemoversikt.riskscenario', verbose_name='Risikoscenario')),
            ],
            options={
                'verbose_name': 'risikoscenario-rammeverk-kobling',
                'verbose_name_plural': 'Risiko: scenario-rammeverk-koblinger',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('scenario', 'framework_node')},
            },
        ),
    ]
