# Generated by Django 4.2.30 on 2026-07-06 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0002_risk_framework_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFrameworkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('read_only', models.BooleanField(default=False, help_text='Når aktivert får medlemmer lesetilgang til rammeverket. Uten dette har medlemmer full redigeringstilgang.', verbose_name='Kun lesetilgang')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_framework_groups_created', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_groups', to='systemoversikt.riskframework', verbose_name='Rammeverk')),
            ],
            options={
                'verbose_name': 'risiko rammeverk-tilgangsgruppe',
                'verbose_name_plural': 'Risiko: rammeverk-tilgangsgrupper',
                'ordering': ['framework__title', 'title'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='RiskFrameworkGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_framework_group_memberships_added', to=settings.AUTH_USER_MODEL, verbose_name='Lagt til av')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='systemoversikt.riskframeworkgroup', verbose_name='Gruppe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_framework_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'verbose_name': 'risiko rammeverk-tilgangsgruppe-medlem',
                'verbose_name_plural': 'Risiko: rammeverk-tilgangsgruppe-medlemmer',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRiskFrameworkGroupMember',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Lagt til av')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframeworkgroup', verbose_name='Gruppe')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'verbose_name': 'historical risiko rammeverk-tilgangsgruppe-medlem',
                'verbose_name_plural': 'historical Risiko: rammeverk-tilgangsgruppe-medlemmer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskFrameworkGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('read_only', models.BooleanField(default=False, help_text='Når aktivert får medlemmer lesetilgang til rammeverket. Uten dette har medlemmer full redigeringstilgang.', verbose_name='Kun lesetilgang')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('framework', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframework', verbose_name='Rammeverk')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical risiko rammeverk-tilgangsgruppe',
                'verbose_name_plural': 'historical Risiko: rammeverk-tilgangsgrupper',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='riskframeworkgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='risk_framework_group_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='riskframeworkgroup',
            constraint=models.UniqueConstraint(fields=('framework', 'title'), name='risk_framework_group_unique_title'),
        ),
    ]
