# Generated by Django 4.2.30 on 2026-07-06 12:53
# 2026-07-06: Drop RiskFrameworkGroup* in one step; reuse virksomhet tilgangsgrupper for rammeverk.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0003_risk_framework_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalriskframework',
            name='virksomhet',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Tilgangsgrupper for denne virksomheten styrer hvem som kan se/redigere rammeverket.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='systemoversikt.virksomhet',
                verbose_name='Virksomhet (tilgangsstyring)',
            ),
        ),
        migrations.AddField(
            model_name='riskframework',
            name='virksomhet',
            field=models.ForeignKey(
                blank=True,
                help_text='Tilgangsgrupper for denne virksomheten styrer hvem som kan se/redigere rammeverket.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='risk_frameworks',
                to='systemoversikt.virksomhet',
                verbose_name='Virksomhet (tilgangsstyring)',
            ),
        ),
        migrations.AddField(
            model_name='riskvirksomhetgroup',
            name='framework_owner_for',
            field=models.ManyToManyField(
                blank=True,
                help_text='Medlemmer kan redigere valgte risikorammeverk (kartlegging, taksonomi, vurderinger).',
                related_name='owner_groups',
                to='systemoversikt.riskframework',
                verbose_name='Eier tilgang rammeverk',
            ),
        ),
        migrations.AddField(
            model_name='riskvirksomhetgroup',
            name='framework_read_for',
            field=models.ManyToManyField(
                blank=True,
                help_text='Medlemmer kan lese sammenstillinger for valgte risikorammeverk.',
                related_name='read_groups',
                to='systemoversikt.riskframework',
                verbose_name='Lesetilgang rammeverk',
            ),
        ),
        migrations.DeleteModel(
            name='RiskFrameworkGroupMember',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskFrameworkGroupMember',
        ),
        migrations.DeleteModel(
            name='RiskFrameworkGroup',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskFrameworkGroup',
        ),
    ]
