# Generated by Django 4.2.30 on 2026-07-06 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0004_risk_framework_virksomhet_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRiskSammenstilling',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
            ],
            options={
                'verbose_name': 'historical risikosammenstilling',
                'verbose_name_plural': 'historical Risiko: sammenstillinger',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskSammenstillingNodeAssessment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('konsekvens_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Konsekvens')),
                ('sannsynlighet_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sannsynlighet')),
                ('begrunnelse', models.TextField(blank=True, default='', verbose_name='Begrunnelse')),
                ('sist_revidert', models.DateField(blank=True, null=True, verbose_name='Sist revidert')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('framework_node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revidert_av', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revidert av')),
            ],
            options={
                'verbose_name': 'historical risikosammenstilling-nodevurdering',
                'verbose_name_plural': 'historical Risiko: sammenstilling-nodevurderinger',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskSammenstillingScenarioLink',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('mapped_at', models.DateTimeField(blank=True, editable=False, verbose_name='Kartlagt')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notat')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('framework_node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mapped_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kartlagt av')),
            ],
            options={
                'verbose_name': 'historical risikosammenstilling-scenario-kobling',
                'verbose_name_plural': 'historical Risiko: sammenstilling-scenario-koblinger',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RiskSammenstilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('title', models.CharField(max_length=200, verbose_name='Tittel')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_sammenstillinger_created', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
            ],
            options={
                'verbose_name': 'risikosammenstilling',
                'verbose_name_plural': 'Risiko: sammenstillinger',
                'ordering': ['-sist_oppdatert', 'title'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='RiskSammenstillingNodeAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('konsekvens_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Konsekvens')),
                ('sannsynlighet_nivaa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sannsynlighet')),
                ('begrunnelse', models.TextField(blank=True, default='', verbose_name='Begrunnelse')),
                ('sist_revidert', models.DateField(blank=True, null=True, verbose_name='Sist revidert')),
                ('framework_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sammenstilling_assessments', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('revidert_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_sammenstilling_assessments_revised', to=settings.AUTH_USER_MODEL, verbose_name='Revidert av')),
                ('sammenstilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_assessments', to='systemoversikt.risksammenstilling', verbose_name='Sammenstilling')),
            ],
            options={
                'verbose_name': 'risikosammenstilling-nodevurdering',
                'verbose_name_plural': 'Risiko: sammenstilling-nodevurderinger',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('sammenstilling', 'framework_node')},
            },
        ),
        migrations.CreateModel(
            name='RiskSammenstillingScenarioLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('mapped_at', models.DateTimeField(auto_now_add=True, verbose_name='Kartlagt')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notat')),
                ('framework_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sammenstilling_links', to='systemoversikt.riskframeworknode', verbose_name='Rammeverk-node')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_sammenstilling_links_created', to=settings.AUTH_USER_MODEL, verbose_name='Kartlagt av')),
                ('sammenstilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_links', to='systemoversikt.risksammenstilling', verbose_name='Sammenstilling')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sammenstilling_links', to='systemoversikt.riskscenario', verbose_name='Risikoscenario')),
            ],
            options={
                'verbose_name': 'risikosammenstilling-scenario-kobling',
                'verbose_name_plural': 'Risiko: sammenstilling-scenario-koblinger',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('sammenstilling', 'scenario', 'framework_node')},
            },
        ),
        migrations.RemoveField(
            model_name='historicalriskvirksomhetnodeassessment',
            name='framework_node',
        ),
        migrations.RemoveField(
            model_name='historicalriskvirksomhetnodeassessment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalriskvirksomhetnodeassessment',
            name='revidert_av',
        ),
        migrations.RemoveField(
            model_name='historicalriskvirksomhetnodeassessment',
            name='virksomhet',
        ),
        migrations.AlterUniqueTogether(
            name='riskscenarioframeworklink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='riskscenarioframeworklink',
            name='framework_node',
        ),
        migrations.RemoveField(
            model_name='riskscenarioframeworklink',
            name='mapped_by',
        ),
        migrations.RemoveField(
            model_name='riskscenarioframeworklink',
            name='scenario',
        ),
        migrations.AlterUniqueTogether(
            name='riskvirksomhetnodeassessment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='riskvirksomhetnodeassessment',
            name='framework_node',
        ),
        migrations.RemoveField(
            model_name='riskvirksomhetnodeassessment',
            name='revidert_av',
        ),
        migrations.RemoveField(
            model_name='riskvirksomhetnodeassessment',
            name='virksomhet',
        ),
        migrations.AlterModelOptions(
            name='historicalriskframework',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical risikorammeverk-mal', 'verbose_name_plural': 'historical Risiko: rammeverk-maler'},
        ),
        migrations.AlterModelOptions(
            name='riskframework',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['title'], 'verbose_name': 'risikorammeverk-mal', 'verbose_name_plural': 'Risiko: rammeverk-maler'},
        ),
        migrations.RemoveField(
            model_name='historicalriskframework',
            name='virksomhet',
        ),
        migrations.RemoveField(
            model_name='riskframework',
            name='virksomhet',
        ),
        migrations.RemoveField(
            model_name='riskvirksomhetgroup',
            name='framework_owner_for',
        ),
        migrations.RemoveField(
            model_name='riskvirksomhetgroup',
            name='framework_read_for',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskScenarioFrameworkLink',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskVirksomhetNodeAssessment',
        ),
        migrations.DeleteModel(
            name='RiskScenarioFrameworkLink',
        ),
        migrations.DeleteModel(
            name='RiskVirksomhetNodeAssessment',
        ),
        migrations.AddField(
            model_name='risksammenstilling',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sammenstillinger', to='systemoversikt.riskframework', verbose_name='Mal'),
        ),
        migrations.AddField(
            model_name='risksammenstilling',
            name='owner_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sammenstillinger', to='systemoversikt.riskvirksomhetgroup', verbose_name='Eiergruppe'),
        ),
        migrations.AddField(
            model_name='historicalrisksammenstillingscenariolink',
            name='sammenstilling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.risksammenstilling', verbose_name='Sammenstilling'),
        ),
        migrations.AddField(
            model_name='historicalrisksammenstillingscenariolink',
            name='scenario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskscenario', verbose_name='Risikoscenario'),
        ),
        migrations.AddField(
            model_name='historicalrisksammenstillingnodeassessment',
            name='sammenstilling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.risksammenstilling', verbose_name='Sammenstilling'),
        ),
        migrations.AddField(
            model_name='historicalrisksammenstilling',
            name='framework',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskframework', verbose_name='Mal'),
        ),
        migrations.AddField(
            model_name='historicalrisksammenstilling',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrisksammenstilling',
            name='owner_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskvirksomhetgroup', verbose_name='Eiergruppe'),
        ),
        migrations.AddConstraint(
            model_name='risksammenstilling',
            constraint=models.UniqueConstraint(fields=('owner_group', 'title'), name='risk_sammenstilling_unique_title_per_group'),
        ),
    ]
