# Generated by Django 4.2.30 on 2026-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0005_risk_sammenstilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalriskaction',
            name='eskaleres',
            field=models.BooleanField(default=False, help_text='Tiltaket kan ikke løses på lokalt nivå.', verbose_name='Må eskaleres'),
        ),
        migrations.AddField(
            model_name='riskaction',
            name='eskaleres',
            field=models.BooleanField(default=False, help_text='Tiltaket kan ikke løses på lokalt nivå.', verbose_name='Må eskaleres'),
        ),
    ]
