# Generated by Django 4.2.30 on 2026-07-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0008_infoblox_host_networkcontainer_eas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalriskscope',
            name='beskrivelse',
            field=models.TextField(blank=True, default='', help_text='Omfangsbeskrivelse som inngår i den arkiverte risikovurderingsrapporten.', verbose_name='Beskrivelse'),
        ),
    ]
