# Generated by Django 4.2.30 on 2026-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0010_risksammenstilling_reader_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(db_index=True, editable=False, unique=True, verbose_name='Snapshot-ID')),
                ('source_type', models.CharField(choices=[('collection', 'Risikosamling'), ('sammenstilling', 'Risikosammenstilling')], db_index=True, max_length=20, verbose_name='Kildetype')),
                ('source_pk', models.PositiveIntegerField(db_index=True, verbose_name='Kilde-ID')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='Tatt')),
                ('time_bin', models.CharField(choices=[('daily', 'Daglig'), ('weekly', 'Ukentlig'), ('monthly', 'Månedlig'), ('yearly', 'Årlig')], db_index=True, default='daily', max_length=10, verbose_name='Tidsbin')),
                ('template_version', models.PositiveSmallIntegerField(default=1, verbose_name='Malversjon')),
                ('json_schema_version', models.PositiveSmallIntegerField(default=1, verbose_name='JSON-skjemaversjon')),
                ('payload', models.JSONField(verbose_name='Innhold')),
                ('payload_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('title', models.CharField(blank=True, default='', help_text='Denormalisert tittel for lister (samling/sammenstilling).', max_length=300, verbose_name='Tittel')),
            ],
            options={
                'verbose_name': 'risiko-snapshot',
                'verbose_name_plural': 'Risiko: snapshots',
                'ordering': ['-captured_at'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'indexes': [models.Index(fields=['source_type', 'source_pk', '-captured_at'], name='systemovers_source__b4d8c5_idx')],
            },
        ),
    ]
