# Generated by Django 4.2.30 on 2026-07-09 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0012_riskarchive_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('event_type', models.CharField(max_length=50, verbose_name='Hendelsestype')),
                ('message', models.TextField(verbose_name='Melding')),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='systemoversikt.riskframework', verbose_name='Mal')),
                ('sammenstilling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='systemoversikt.risksammenstilling', verbose_name='Sammenstilling')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='systemoversikt.riskscope', verbose_name='Risikosamling')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'verbose_name_plural': 'System: Risikoaktivitet',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'indexes': [models.Index(fields=['scope', 'opprettet'], name='systemovers_scope_i_3f520e_idx'), models.Index(fields=['sammenstilling', 'opprettet'], name='systemovers_sammens_ca578a_idx')],
            },
        ),
    ]
