# Generated by Django 4.2.30 on 2026-08-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0013_riskactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalriskaction',
            name='status',
            field=models.CharField(choices=[('forslag', 'Forslag'), ('besluttet', 'Besluttet'), ('under_arbeid', 'Under arbeid'), ('kontinuerlig_oppfolging', 'Kontinuerlig oppfølging'), ('utfort', 'Utført')], default='forslag', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='riskaction',
            name='status',
            field=models.CharField(choices=[('forslag', 'Forslag'), ('besluttet', 'Besluttet'), ('under_arbeid', 'Under arbeid'), ('kontinuerlig_oppfolging', 'Kontinuerlig oppfølging'), ('utfort', 'Utført')], default='forslag', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='risksnapshot',
            name='json_schema_version',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='JSON-skjemaversjon'),
        ),
        migrations.CreateModel(
            name='RiskActionUnntak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('beskrivelse', models.TextField(help_text='Hvor / hva unntaket gjelder.', verbose_name='Unntak')),
                ('begrunnelse', models.TextField(blank=True, default='', help_text='Hvorfor tiltaket ikke kunne implementeres her.', verbose_name='Begrunnelse')),
                ('gyldig_til', models.DateField(blank=True, null=True, verbose_name='Gyldig til')),
                ('aktiv', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unntak', to='systemoversikt.riskaction', verbose_name='Tiltak')),
                ('opprettet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_action_unntak_created', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
                ('systemer', models.ManyToManyField(blank=True, related_name='risk_action_unntak', to='systemoversikt.system', verbose_name='Systemer')),
            ],
            options={
                'verbose_name': 'risikotiltak-unntak',
                'verbose_name_plural': 'Risiko: tiltak-unntak',
                'ordering': ['-aktiv', '-opprettet', 'pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRiskActionUnntak',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('beskrivelse', models.TextField(help_text='Hvor / hva unntaket gjelder.', verbose_name='Unntak')),
                ('begrunnelse', models.TextField(blank=True, default='', help_text='Hvorfor tiltaket ikke kunne implementeres her.', verbose_name='Begrunnelse')),
                ('gyldig_til', models.DateField(blank=True, null=True, verbose_name='Gyldig til')),
                ('aktiv', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('action', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.riskaction', verbose_name='Tiltak')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opprettet_av', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av')),
            ],
            options={
                'verbose_name': 'historical risikotiltak-unntak',
                'verbose_name_plural': 'historical Risiko: tiltak-unntak',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
