# Generated by Django 4.2.30 on 2026-08-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0015_azureapplication_approleassignmentrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virksomhet',
            name='uke_kam_referanse',
            field=models.ManyToManyField(blank=True, help_text='Dette er deres kundeansvarlig i DIG/OKF. Feltet bør oppdateres av DIG/OKF.', related_name='virksomhet_uke_kam', to='systemoversikt.ansvarlig', verbose_name='Kundeansvarlig fra intern tjenesteleverandør'),
        ),
    ]
