# 2026-09-14: SystemBruk tatt_i_bruk/avsluttet dates and kommentar verbose_name Innhold (field name unchanged).
# Generated by Django 4.2.30 on 2026-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0016_uke_kam_referanse_dig_okf_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystembruk',
            name='avsluttet',
            field=models.DateField(blank=True, help_text='Datoen systemet ble tatt ut av bruk i virksomheten.', null=True, verbose_name='Avsluttet'),
        ),
        migrations.AddField(
            model_name='historicalsystembruk',
            name='tatt_i_bruk',
            field=models.DateField(blank=True, help_text='Datoen systemet ble tatt i bruk i virksomheten.', null=True, verbose_name='Tatt i bruk'),
        ),
        migrations.AddField(
            model_name='systembruk',
            name='avsluttet',
            field=models.DateField(blank=True, help_text='Datoen systemet ble tatt ut av bruk i virksomheten.', null=True, verbose_name='Avsluttet'),
        ),
        migrations.AddField(
            model_name='systembruk',
            name='tatt_i_bruk',
            field=models.DateField(blank=True, help_text='Datoen systemet ble tatt i bruk i virksomheten.', null=True, verbose_name='Tatt i bruk'),
        ),
        migrations.AlterField(
            model_name='historicalsystembruk',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Utdyp hva systemet brukes til hos din virksomhet.', null=True, verbose_name='Innhold'),
        ),
        migrations.AlterField(
            model_name='systembruk',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Utdyp hva systemet brukes til hos din virksomhet.', null=True, verbose_name='Innhold'),
        ),
    ]
