# 2026-09-14: Rename System.er_arkiv label; add dato_godkjent_elektronisk_arkiv (and historical).
# Generated by Django 4.2.30 on 2026-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0017_systembruk_tatt_i_bruk_avsluttet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystem',
            name='dato_godkjent_elektronisk_arkiv',
            field=models.DateField(blank=True, help_text='Datoen systemet ble godkjent som elektronisk arkiv.', null=True, verbose_name='Dato godkjent som elektronisk arkiv'),
        ),
        migrations.AddField(
            model_name='system',
            name='dato_godkjent_elektronisk_arkiv',
            field=models.DateField(blank=True, help_text='Datoen systemet ble godkjent som elektronisk arkiv.', null=True, verbose_name='Dato godkjent som elektronisk arkiv'),
        ),
        migrations.AlterField(
            model_name='historicalsystem',
            name='er_arkiv',
            field=models.BooleanField(default=False, help_text='Krysses av dersom systemet er godkjent som elektronisk arkiv i henhold til arkivlovverk.', verbose_name='Godkjent som elektronisk arkiv?'),
        ),
        migrations.AlterField(
            model_name='system',
            name='er_arkiv',
            field=models.BooleanField(default=False, help_text='Krysses av dersom systemet er godkjent som elektronisk arkiv i henhold til arkivlovverk.', verbose_name='Godkjent som elektronisk arkiv?'),
        ),
    ]
