# 2026-09-14: System.produksjonsformater JSON multi-select (PDF, JPG, DOCX) plus historical copy.
# Generated by Django 4.2.30 on 2026-09-14 18:16

from django.db import migrations, models
import systemoversikt.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0018_system_er_arkiv_godkjent_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystem',
            name='produksjonsformater',
            field=models.JSONField(blank=True, default=list, help_text='Velg ett eller flere produksjonsformater systemet benytter.', validators=[systemoversikt.models.validate_produksjonsformater], verbose_name='Produksjonsformater'),
        ),
        migrations.AddField(
            model_name='system',
            name='produksjonsformater',
            field=models.JSONField(blank=True, default=list, help_text='Velg ett eller flere produksjonsformater systemet benytter.', validators=[systemoversikt.models.validate_produksjonsformater], verbose_name='Produksjonsformater'),
        ),
    ]
