# 2026-09-15: ArkivOverforing + HistoricalArkivOverforing; unique (avsender_bruk, mottaker_system).
# Generated by Django 4.2.30 on 2026-09-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0019_system_produksjonsformater'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArkivOverforing',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opprettet', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('dato_start', models.DateField(blank=True, null=True, verbose_name='Dato start overføring')),
                ('dato_avsluttet', models.DateField(blank=True, null=True, verbose_name='Dato overføring avsluttet')),
                ('kommentar', models.TextField(blank=True, help_text='Beskrivelse av hva som er overført.', null=True, verbose_name='Kommentar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('avsender_bruk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.systembruk', verbose_name='Avsender (systembruk)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mottaker_system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.system', verbose_name='Mottakersystem')),
            ],
            options={
                'verbose_name': 'historical arkivoverføring',
                'verbose_name_plural': 'historical Systemoversikt: Arkivoverføringer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ArkivOverforing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('dato_start', models.DateField(blank=True, null=True, verbose_name='Dato start overføring')),
                ('dato_avsluttet', models.DateField(blank=True, null=True, verbose_name='Dato overføring avsluttet')),
                ('kommentar', models.TextField(blank=True, help_text='Beskrivelse av hva som er overført.', null=True, verbose_name='Kommentar')),
                ('avsender_bruk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkivoverforinger_som_avsender', to='systemoversikt.systembruk', verbose_name='Avsender (systembruk)')),
                ('mottaker_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkivoverforinger_som_mottaker', to='systemoversikt.system', verbose_name='Mottakersystem')),
            ],
            options={
                'verbose_name': 'arkivoverføring',
                'verbose_name_plural': 'Systemoversikt: Arkivoverføringer',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddConstraint(
            model_name='arkivoverforing',
            constraint=models.UniqueConstraint(fields=('avsender_bruk', 'mottaker_system'), name='unique_arkivoverforing_bruk_mottaker'),
        ),
    ]
