# 2026-09-15: SystemBruk.systemeier_kontaktpersoner_referanse display “Lokal informasjonseier (person)” (field name unchanged).
# Generated by Django 4.2.30 on 2026-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0020_arkivoverforing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systembruk',
            name='systemeier_kontaktpersoner_referanse',
            field=models.ManyToManyField(blank=True, help_text='Dersom fellesløsning på applikasjonshotell, hvilke roller/personer fyller rollen som lokal eier?', related_name='systembruk_systemeier_kontaktpersoner', to='systemoversikt.ansvarlig', verbose_name='Lokal informasjonseier (person)'),
        ),
    ]
