# 2026-09-15: SystemBruk.kommentar (Innhold) help text – virksomhet-specific use beyond systemeier approval.
# Generated by Django 4.2.30 on 2026-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0021_systembruk_lokal_informasjonseier_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystembruk',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Beskriv om virksomheten bruker systemet til noe mer enn det systemeier har godkjent, om det er spesialtilpasninger for virksomheten, og annen relevant informasjon om bruken som er virksomhetsspesifikk.', null=True, verbose_name='Innhold'),
        ),
        migrations.AlterField(
            model_name='systembruk',
            name='kommentar',
            field=models.TextField(blank=True, help_text='Beskriv om virksomheten bruker systemet til noe mer enn det systemeier har godkjent, om det er spesialtilpasninger for virksomheten, og annen relevant informasjon om bruken som er virksomhetsspesifikk.', null=True, verbose_name='Innhold'),
        ),
    ]
