# 2026-09-15: InformasjonsKategori (OKA) lookup, System M2M and SystemBruk tillegg/unntak.
# Generated by Django 4.2.30 on 2026-09-15 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemoversikt', '0022_systembruk_innhold_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformasjonsKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('kode', models.CharField(help_text='Visningskode fra OKA, f.eks. A1 - 01.', max_length=30, verbose_name='Kode')),
                ('kode_normalisert', models.CharField(help_text='Unik nøkkel for import (mellomrom rundt bindestrek normalisert).', max_length=30, unique=True, verbose_name='Normalisert kode')),
                ('tittel', models.CharField(max_length=400, verbose_name='Tittel')),
                ('nivaa', models.CharField(choices=[('hovedfunksjon', 'Hovedfunksjon'), ('funksjon', 'Funksjon'), ('underfunksjon', 'Underfunksjon')], db_index=True, max_length=20, verbose_name='Nivå')),
                ('her_legges', models.TextField(blank=True, default='', verbose_name='Her legges')),
                ('bk_vurdering', models.TextField(blank=True, default='', verbose_name='Bevarings- og kassasjonsvurdering')),
                ('tidligere_arkivnokkel', models.TextField(blank=True, default='', verbose_name='Tidligere arkivnøkkel')),
                ('aktuelt_lovverk', models.TextField(blank=True, default='', verbose_name='Aktuelt lovverk')),
                ('kommentar', models.TextField(blank=True, default='', verbose_name='Kommentar')),
                ('aktiv', models.BooleanField(db_index=True, default=True, help_text='Deaktiveres ved re-import hvis koden ikke lenger finnes i OKA-filen.', verbose_name='Aktiv')),
                ('rekkefolge', models.PositiveIntegerField(default=0, verbose_name='Rekkefølge')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barn', to='systemoversikt.informasjonskategori', verbose_name='Overordnet kategori')),
            ],
            options={
                'verbose_name': 'informasjonskategori',
                'verbose_name_plural': 'Dokumentasjon: Informasjonskategorier (OKA)',
                'ordering': ['rekkefolge', 'kode_normalisert'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalSystemBrukInformasjonsKategori',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('status', models.CharField(choices=[('tillegg', 'Tillegg'), ('unntak', 'Unntak (brukes ikke)')], max_length=20, verbose_name='Status')),
                ('begrunnelse', models.TextField(blank=True, default='', help_text='Valgfri begrunnelse, særlig ved unntak fra en standardkategori.', verbose_name='Begrunnelse')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'nivaa': 'underfunksjon'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.informasjonskategori', verbose_name='Informasjonskategori')),
                ('systembruk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.systembruk', verbose_name='Systembruk')),
            ],
            options={
                'verbose_name': 'historical systembruk-informasjonskategori',
                'verbose_name_plural': 'historical Organisasjon: Systembruk informasjonskategorier',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInformasjonsKategori',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sist_oppdatert', models.DateTimeField(blank=True, editable=False, verbose_name='Sist oppdatert')),
                ('kode', models.CharField(help_text='Visningskode fra OKA, f.eks. A1 - 01.', max_length=30, verbose_name='Kode')),
                ('kode_normalisert', models.CharField(db_index=True, help_text='Unik nøkkel for import (mellomrom rundt bindestrek normalisert).', max_length=30, verbose_name='Normalisert kode')),
                ('tittel', models.CharField(max_length=400, verbose_name='Tittel')),
                ('nivaa', models.CharField(choices=[('hovedfunksjon', 'Hovedfunksjon'), ('funksjon', 'Funksjon'), ('underfunksjon', 'Underfunksjon')], db_index=True, max_length=20, verbose_name='Nivå')),
                ('her_legges', models.TextField(blank=True, default='', verbose_name='Her legges')),
                ('bk_vurdering', models.TextField(blank=True, default='', verbose_name='Bevarings- og kassasjonsvurdering')),
                ('tidligere_arkivnokkel', models.TextField(blank=True, default='', verbose_name='Tidligere arkivnøkkel')),
                ('aktuelt_lovverk', models.TextField(blank=True, default='', verbose_name='Aktuelt lovverk')),
                ('kommentar', models.TextField(blank=True, default='', verbose_name='Kommentar')),
                ('aktiv', models.BooleanField(db_index=True, default=True, help_text='Deaktiveres ved re-import hvis koden ikke lenger finnes i OKA-filen.', verbose_name='Aktiv')),
                ('rekkefolge', models.PositiveIntegerField(default=0, verbose_name='Rekkefølge')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='systemoversikt.informasjonskategori', verbose_name='Overordnet kategori')),
            ],
            options={
                'verbose_name': 'historical informasjonskategori',
                'verbose_name_plural': 'historical Dokumentasjon: Informasjonskategorier (OKA)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='system',
            name='informasjonskategorier',
            field=models.ManyToManyField(blank=True, help_text='Standard informasjonskategorier (mest detaljerte OKA-nivå) systemet behandler. Virksomheter kan legge til eller unnta kategorier på systembruk.', limit_choices_to={'aktiv': True, 'nivaa': 'underfunksjon'}, related_name='systemer_informasjonskategori', to='systemoversikt.informasjonskategori', verbose_name='Informasjonskategorier (OKA)'),
        ),
        migrations.CreateModel(
            name='SystemBrukInformasjonsKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('status', models.CharField(choices=[('tillegg', 'Tillegg'), ('unntak', 'Unntak (brukes ikke)')], max_length=20, verbose_name='Status')),
                ('begrunnelse', models.TextField(blank=True, default='', help_text='Valgfri begrunnelse, særlig ved unntak fra en standardkategori.', verbose_name='Begrunnelse')),
                ('kategori', models.ForeignKey(limit_choices_to={'nivaa': 'underfunksjon'}, on_delete=django.db.models.deletion.PROTECT, related_name='systembruk_koblinger', to='systemoversikt.informasjonskategori', verbose_name='Informasjonskategori')),
                ('systembruk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informasjonskategori_koblinger', to='systemoversikt.systembruk', verbose_name='Systembruk')),
            ],
            options={
                'verbose_name': 'systembruk-informasjonskategori',
                'verbose_name_plural': 'Organisasjon: Systembruk informasjonskategorier',
                'ordering': ['status', 'kategori__rekkefolge', 'kategori__kode_normalisert'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('systembruk', 'kategori')},
            },
        ),
    ]
