# 2026-09-15: InformasjonsKategori.tittel max_length 400→800 – OKA Excel titles exceed 400 on Postgres.
# Generated by Django 4.2.30 on 2026-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0023_informasjonskategori_oka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinformasjonskategori',
            name='tittel',
            field=models.CharField(max_length=800, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='informasjonskategori',
            name='tittel',
            field=models.CharField(max_length=800, verbose_name='Tittel'),
        ),
    ]
