# 2026-09-21: System tilgjengelighetsvurdering/kritisk_kapabilitet/service_offerings help texts for systemprioritering.
# Generated by Django 4.2.30 on 2026-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0024_informasjonskategori_tittel_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystem',
            name='tilgjengelighetsvurdering',
            field=models.BigIntegerField(blank=True, choices=[(1, '🔴5 Svært alvorlig'), (2, '🔴4 Alvorlig'), (3, '🟡3 Moderat'), (4, '🟢2 Lav'), (5, '🟢1 Ubetydelig'), (6, '0 Ikke vurdert')], default=6, help_text='Hvor kritisk er det at systemet virker? Feltet brukes for å beregne systemprioritering.<br>Eksempler basert på liv og helse / måloppnåelse:<br>• 5 Svært alvorlig: Dødsfall eller flere personer rammes av alvorlig varig funksjonsnedsettelse eller skade. / Manglende oppnåelse av kritiske mål i virksomheten.<br>• 4 Alvorlig: Alvorlig personskade eller varig funksjonsnedsettelse. / Manglende oppnåelse av mindre kritiske mål i virksomheten.<br>• 3 Moderat: Mindre alvorlig personskade. / Moderat innvirkning på oppnåelse av virksomhetens mål.<br>• 2 Lav: Småskader. / Liten innvirkning på oppnåelse av virksomhetens mål.<br>• 1 Ubetydelig: Ingen skade. / Ubetydelig innvirkning på oppnåelse av virksomhetens mål.', null=True, verbose_name='Tilgjengelighetsvurdering'),
        ),
        migrations.AlterField(
            model_name='system',
            name='kritisk_kapabilitet',
            field=models.ManyToManyField(blank=True, help_text='Understøtter systemet en kritisk funksjon? Kategorier basert på rammeverket fra DSB. Feltet brukes for å beregne systemprioritering.', related_name='systemer', to='systemoversikt.kritiskkapabilitet', verbose_name='Kritisk kapabilitet'),
        ),
        migrations.AlterField(
            model_name='system',
            name='service_offerings',
            field=models.ManyToManyField(blank=True, help_text='Feltet brukes for å beregne systemprioritering. Når systemet er koblet til riktig tjenesteleveranse hos driftsleverandør, vil systemets tjenestenivå og driftskritikalitet automatisk hentes inn. Her velger du alle service offerings knyttet til dette systemet. Ta kontakt med DIG om du trenger hjelp med denne koblingen.', related_name='system', to='systemoversikt.cmdbref', verbose_name='Service offerings fra Sopra Steria CMDB'),
        ),
        migrations.AlterField(
            model_name='system',
            name='tilgjengelighetsvurdering',
            field=models.BigIntegerField(blank=True, choices=[(1, '🔴5 Svært alvorlig'), (2, '🔴4 Alvorlig'), (3, '🟡3 Moderat'), (4, '🟢2 Lav'), (5, '🟢1 Ubetydelig'), (6, '0 Ikke vurdert')], default=6, help_text='Hvor kritisk er det at systemet virker? Feltet brukes for å beregne systemprioritering.<br>Eksempler basert på liv og helse / måloppnåelse:<br>• 5 Svært alvorlig: Dødsfall eller flere personer rammes av alvorlig varig funksjonsnedsettelse eller skade. / Manglende oppnåelse av kritiske mål i virksomheten.<br>• 4 Alvorlig: Alvorlig personskade eller varig funksjonsnedsettelse. / Manglende oppnåelse av mindre kritiske mål i virksomheten.<br>• 3 Moderat: Mindre alvorlig personskade. / Moderat innvirkning på oppnåelse av virksomhetens mål.<br>• 2 Lav: Småskader. / Liten innvirkning på oppnåelse av virksomhetens mål.<br>• 1 Ubetydelig: Ingen skade. / Ubetydelig innvirkning på oppnåelse av virksomhetens mål.', null=True, verbose_name='Tilgjengelighetsvurdering'),
        ),
    ]
