# 2026-09-21: Systemforvalter (personer) help text – monthly e-mail reminder (epost_generisk_varsling, day 10).
# Generated by Django 4.2.30 on 2026-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0025_system_prioritering_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='systemforvalter_kontaktpersoner_referanse',
            field=models.ManyToManyField(blank=True, help_text='Person(er) med operativt forvalteransvar. Alle som er listet her får en e-postpåminnelse den 10. i hver måned. Hvis du ikke finner personen du leter etter, kan du legge til med det grønne +-tegnet.', related_name='system_forvalter_for', to='systemoversikt.ansvarlig', verbose_name='Systemforvalter (personer)'),
        ),
    ]
