# 2026-09-25: Sarbarhetssak – CVE cases tracked under sikkerhet (list, detail, create, edit).
# Generated by Django 4.2.30 on 2026-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0026_systemforvalter_kontaktpersoner_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarbarhetssak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opprettet', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Opprettet')),
                ('sist_oppdatert', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('cve', models.CharField(help_text='For eksempel CVE-2024-12345.', max_length=40, verbose_name='CVE-nummer')),
                ('tittel', models.CharField(max_length=300, verbose_name='Tittel')),
                ('tiltakseier', models.CharField(choices=[('driftsleverandor', 'Driftsleverandør'), ('digitaliseringsetaten', 'Digitaliseringsetaten'), ('systemeier', 'Systemeier')], max_length=32, verbose_name='Tiltakseier')),
                ('saksreferanse', models.CharField(blank=True, default='', help_text='Saksnummer eller URL.', max_length=500, verbose_name='Referanse til saksbehandlingssystem')),
                ('saksstatus', models.CharField(choices=[('ny', 'Ny'), ('under_arbeid', 'Under arbeid'), ('lukket', 'Lukket')], default='ny', max_length=32, verbose_name='Saksstatus')),
            ],
            options={
                'verbose_name': 'sårbarhetssak',
                'verbose_name_plural': 'Sårbarhetssaker',
                'ordering': ['-sist_oppdatert', '-pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
