# 2026-09-25: CVE and tiltakseier optional – only title is required. Rename to Sårbarhetsoppfølging.
# Generated by Django 4.2.30 on 2026-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0027_sarbarhetssak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarbarhetssak',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-sist_oppdatert', '-pk'], 'verbose_name': 'sårbarhetsoppfølging', 'verbose_name_plural': 'Sårbarhetsoppfølging'},
        ),
        migrations.AlterField(
            model_name='sarbarhetssak',
            name='cve',
            field=models.CharField(blank=True, default='', help_text='For eksempel CVE-2024-12345.', max_length=40, verbose_name='CVE-nummer'),
        ),
        migrations.AlterField(
            model_name='sarbarhetssak',
            name='tiltakseier',
            field=models.CharField(blank=True, choices=[('driftsleverandor', 'Driftsleverandør'), ('digitaliseringsetaten', 'Digitaliseringsetaten'), ('systemeier', 'Systemeier')], default='', max_length=32, verbose_name='Tiltakseier'),
        ),
    ]
