# 2026-09-25: Free-text status on sårbarhetsoppfølging.
# Generated by Django 4.2.30 on 2026-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0028_sarbarhetssak_optional_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarbarhetssak',
            name='oppgavestatus',
            field=models.TextField(blank=True, default='', help_text='Fritekst om status på oppgaven.', max_length=2000, verbose_name='Status'),
        ),
    ]
