# Generated by Django 4.2.30 on 2026-10-01 13:34
# 2026-10-01: New snapshot defaults (template v2, schema v3) after hovedkategori level became computed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0029_sarbarhetssak_oppgavestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksnapshot',
            name='json_schema_version',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='JSON-skjemaversjon'),
        ),
        migrations.AlterField(
            model_name='risksnapshot',
            name='template_version',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Malversjon'),
        ),
    ]
