# Generated by Django 4.2.30 on 2026-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemoversikt', '0030_alter_risksnapshot_json_schema_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksnapshot',
            name='template_version',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Malversjon'),
        ),
    ]
