#!/bin/sh

# enable virtual environment
source /home/drift23914/metadata/py36-venv/bin/activate

# run batch job
python /home/drift23914/metadata/djangoapp/manage.py ldap_users_paged
python /home/drift23914/metadata/djangoapp/manage.py ldap_drift_medlemskap
python /home/drift23914/metadata/djangoapp/manage.py prk_org
python /home/drift23914/metadata/djangoapp/manage.py ldap_group_paged
python /home/drift23914/metadata/djangoapp/manage.py ldap_ou_paged
python /home/drift23914/metadata/djangoapp/manage.py prk_users
python /home/drift23914/metadata/djangoapp/manage.py prk_forms
python /home/drift23914/metadata/djangoapp/manage.py lookup_adgroup_prk
python /home/drift23914/metadata/djangoapp/manage.py lookup_adgroup_ou
