#!/bin/sh

# make a compressed backup of the "systemoversikt"-folder
tar -zcf /var/kartoteket/backup/app/djangoapp_`date +%F_%H:%M:%S`.tar.gz /home/X/metadata/djangoapp/systemoversikt

cd /var/kartoteket/backup/app/
last=-1; find . -type f -name '*.tar.gz' -printf '%f\0' | sort -nz |
    while read -d '' i; do
        s=$(stat -c '%s' "$i");
        [[ $s = $last ]] && rm "$i";
    last=$s;
done