#!/bin/sh

#!/bin/sh
source /var/kartoteket/virtualenv/py39/bin/activate
cd /var/kartoteket/source/systemoversikt/

python manage.py dumpdata > latest_full_backup.json


# make a compressed backup of the db.sqlite3-file
tar -zcf /var/kartoteket/backup/db/db_`date +%F_%H:%M:%S`.tar.gz /var/kartoteket/source/systemoversikt/latest_full_backup.json

cd /var/kartoteket/backup/db/
last=-1; find . -type f -name '*.tar.gz' -printf '%f\0' | sort -nz |
    while read -d '' i; do
        s=$(stat -c '%s' "$i");
        [[ $s = $last ]] && rm "$i";
    last=$s;
done

# remove files older than 30 days
find /var/kartoteket/backup/db/ -mindepth 1 -mtime +14 -delete

#+x

