#!/bin/sh
source /var/kartoteket/virtualenv/py311/bin/activate
cd /var/kartoteket/source/systemoversikt/

# run a backup
python manage.py dbbackup --compress

# clean up old backups
find /var/kartoteket/source/systemoversikt/dbbackup/ -mindepth 1 -mtime +21 -delete


# run batch AD/HR
python /var/kartoteket/source/systemoversikt/manage.py ldap_users_paged_v2
python /var/kartoteket/source/systemoversikt/manage.py grunndatabasen_org
python /var/kartoteket/source/systemoversikt/manage.py ldap_group_paged_v2
python /var/kartoteket/source/systemoversikt/manage.py ldap_ou_paged
python /var/kartoteket/source/systemoversikt/manage.py ldap_user_group_membership
python /var/kartoteket/source/systemoversikt/manage.py ldap_mail_enabled_groups
python /var/kartoteket/source/systemoversikt/manage.py grunndatabasen_users
#python /var/kartoteket/source/systemoversikt/manage.py lookup_adgroup_prk
python /var/kartoteket/source/systemoversikt/manage.py lookup_adgroup_ou
python /var/kartoteket/source/systemoversikt/manage.py system_koble_adgrp
python /var/kartoteket/source/systemoversikt/manage.py system_telle_koblede_brukere
python /var/kartoteket/source/systemoversikt/manage.py systembruk_opprett_fra_ad_tilgangsgrupper

# run batch SharePoint
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_bss_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_server_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_client_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_database_mssql_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_database_mssql_size_import
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_database_oracle_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_database_oracle_size_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_server_disk_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_vip_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_vlan_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_dns_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_backup_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_network_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_wan_location_updater
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_firewall_importer
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_citrix_publications
python /var/kartoteket/source/systemoversikt/manage.py sharepoint_qualys
python /var/kartoteket/source/systemoversikt/manage.py helsecert_blocklist

# run batch rydde
python /var/kartoteket/source/systemoversikt/manage.py rydde_ansvarlige
python /var/kartoteket/source/systemoversikt/manage.py rydde_leverandorer
python /var/kartoteket/source/systemoversikt/manage.py rydde_generisk
python /var/kartoteket/source/systemoversikt/manage.py rydde_sette_seksjon
python /var/kartoteket/source/systemoversikt/manage.py rydde_inaktive_systemer
python /var/kartoteket/source/systemoversikt/manage.py rydde_virksomhetssystem
python /var/kartoteket/source/systemoversikt/manage.py rapport_avvik
python /var/kartoteket/source/systemoversikt/manage.py lookup_user_o365lisens

# digdir
python /var/kartoteket/source/systemoversikt/manage.py digdir_los

# run batch azure
python /var/kartoteket/source/systemoversikt/manage.py azure_graph_enterprise_applications
python /var/kartoteket/source/systemoversikt/manage.py azure_graph_named_locations
python /var/kartoteket/source/systemoversikt/manage.py azure_graph_conditional_access
# 2026-05-27: Use v2 Azure auth methods job (requested replacement of default command).
python /var/kartoteket/source/systemoversikt/manage.py azure_authentication_methods_v2
python /var/kartoteket/source/systemoversikt/manage.py azure_graph_vulnerabilities
# 2026-06-19: Nightly device code sign-in combo sync (3-day overlap, Pushover on new noteworthy).
python /var/kartoteket/source/systemoversikt/manage.py device_code_signin_sync

# run batch e-mail
python /var/kartoteket/source/systemoversikt/manage.py azure_graph_nokkelvarsel
python /var/kartoteket/source/systemoversikt/manage.py epost_avtaleutlop
python /var/kartoteket/source/systemoversikt/manage.py epost_generisk_varsling
python /var/kartoteket/source/systemoversikt/manage.py send_mail

# generere grafer av datamodellen
python /var/kartoteket/source/systemoversikt/manage.py graph_models systemoversikt -a -X "*Historical*, *UBW*" --hide-edge-labels -o /var/kartoteket/source/systemoversikt/static/datamodell.png
python /var/kartoteket/source/systemoversikt/manage.py graph_models systemoversikt -a -d -X "*Historical*, *UBW*" --hide-edge-labels -o /var/kartoteket/source/systemoversikt/static/datamodell_enkel.png

# run certipy-ad
cd /var/kartoteket/source/systemoversikt/systemoversikt/pki # files need to be here
python /var/kartoteket/source/systemoversikt/manage.py certipy-ad
cd /var/kartoteket/source/systemoversikt/



