#!/bin/sh

# enable virtual environment
source /home/X/metadata/py36-venv/bin/activate

# run batch job
python /home/X/metadata/djangoapp/manage.py epost_avtaleutlop
python /home/X/metadata/djangoapp/manage.py send_mail
