#!/bin/sh

# enable virtual environment
source /home/X/metadata/py36-venv/bin/activate

cd /home/X/metadata/djangoapp/


export http_proxy="http://user:pass@inetproxy.oslofelles.oslo.kommune.no:3128"
export https_proxy="http://user:pass@inetproxy.oslofelles.oslo.kommune.no:3128"

# run batch job
python /home/X/metadata/djangoapp/manage.py sharepoint_bss_updater
python /home/X/metadata/djangoapp/manage.py sharepoint_server_updater
python /home/X/metadata/djangoapp/manage.py sharepoint_client_updater
python /home/X/metadata/djangoapp/manage.py prk_maskinadm
python /home/X/metadata/djangoapp/manage.py sharepoint_database_mssql_updater
python /home/X/metadata/djangoapp/manage.py sharepoint_database_oracle_updater
python /home/X/metadata/djangoapp/manage.py sharepoint_server_disk_updater
python /home/X/metadata/djangoapp/manage.py sharepoint_vip_updater
python /home/X/metadata/djangoapp/manage.py sharepoint_vlan_updater

