#!/bin/sh
source ~/metadata/py36-venv/bin/activate
cd metadata/djangoapp/

# enable proxy
export http_proxy="http://user:pass@inetproxy.oslofelles.oslo.kommune.no:3128"
export https_proxy="http://user:pass@inetproxy.oslofelles.oslo.kommune.no:3128"

